<script lang="ts">
 import { onMount } from 'svelte';
 import { api, USE_MOCK } from '$lib/api';
 import { safeMarkdown } from '$lib/markdown';
 import type { ApiError, Conversation, Message, Model, Usage, User } from '$lib/types';
 let currentUser:User|null=null, username='alice', password='demo', loginError='', loading=false;
 let models:Model[]=[], conversations:Conversation[]=[], current:Conversation|null=null, messages:Message[]=[], prompt='', notice='', streamController:AbortController|null=null;
 let usages:Usage[]=[], usageModel='', from='', to='', showUsage=false, renameMode=false;
 const errorMessage=(e:unknown) => { const x=e as ApiError; return x?.message || '请求未完成，请稍后重试'; };
 async function bootstrap(){ try { currentUser=await api.me(); await loadChat(); } catch { currentUser=null; } }
 onMount(bootstrap);
 async function login(){ loading=true; loginError=''; try{ currentUser=await api.login(username,password); await loadChat(); }catch(e){loginError=errorMessage(e)}finally{loading=false} }
 async function logout(){ await api.logout(); currentUser=null; current=null; messages=[]; }
 async function loadChat(){ models=await api.models(); conversations=await api.conversations(); if(current){ const found=conversations.find(c=>c.id===current?.id); if(found) await open(found); else current=null; } }
 async function create(){ if(!models[0]) return; try{ current=await api.createConversation(models[0].id); await loadChat(); messages=[]; }catch(e){notice=errorMessage(e)} }
 async function open(c:Conversation){ current=c; const response=await api.messages(c.id); messages=response.items; notice=c.status==='readonly'?'该模型授权已撤销：历史只读。':''; }
 async function remove(c:Conversation){ await api.remove(c.id); if(current?.id===c.id){current=null;messages=[]} await loadChat(); }
 async function rename(){ if(!current) return; current=await api.rename(current.id,current.title); renameMode=false; await loadChat(); }
 async function send(){ if(!current || !prompt.trim() || current.status!=='active' || streamController) return; const content=prompt.trim(); prompt=''; notice=''; streamController=new AbortController(); let assistant:Message={id:'streaming',role:'assistant',content:'',status:'completed',created_at:new Date().toISOString()}; messages=[...messages,{id:`local_${Date.now()}`,role:'user',content,status:'completed',created_at:new Date().toISOString()},assistant];
 try { for await(const event of api.send(current.id,content,streamController.signal)){ if(event.event==='text_delta'){ assistant={...assistant,content:assistant.content+String(event.data.delta||'')}; messages=[...messages.slice(0,-1),assistant]; } if(event.event==='error') notice=String(event.data.message); if(event.event==='done' && event.data.finish_reason==='aborted') notice='生成已中止'; } await open(current); await loadChat(); } catch(e){ if(!streamController?.signal.aborted) { messages=messages.filter(m=>m.id!==assistant.id); notice=errorMessage(e); } } finally { streamController=null; }
 }
 async function stop(){ if(current && streamController){ try{await api.abort(current.id)}catch(e){notice=errorMessage(e)} finally{streamController.abort()} } }
 async function loadUsage(){ usages=await api.usage(from||undefined,to||undefined,usageModel||undefined); }
 $: selectedModel=models.find(m=>m.id===current?.model_id);
</script>

{#if !currentUser}
 <main class="login"><section><h1>Terminal Agent Hub</h1><p>会话 UI（{USE_MOCK ? '独立 mock 模式' : 'REST/SSE 模式'}）</p><form on:submit|preventDefault={login}><label>用户名<input bind:value={username} autocomplete="username" /></label><label>密码<input bind:value={password} type="password" autocomplete="current-password" /></label>{#if loginError}<div class="error" role="alert">{loginError}</div>{/if}<button disabled={loading}>{loading?'登录中…':'登录'}</button></form><small>演示：alice / demo。试用 disabled、limited 或错误密码查看安全提示。</small></section></main>
{:else}
 <main class="app"><aside><header><strong>TAH</strong><button class="link" on:click={logout}>退出</button></header><button class="new" on:click={create} disabled={!models.length}>＋ 新建会话</button>{#if !models.length}<p class="empty">暂无可用模型。请联系管理员授权后重试。</p>{/if}<nav>{#each conversations as c}<div class:chosen={current?.id===c.id}><button on:click={()=>open(c)}>{c.title}<small>{c.status==='readonly'?'只读':''}</small></button><button aria-label="删除会话" class="icon" on:click={()=>remove(c)}>×</button></div>{/each}</nav><button class="usage" on:click={()=>{showUsage=!showUsage;loadUsage()}}>我的用量</button></aside>
 <section class="chat"><header class="chat-head">{#if current}<div>{#if renameMode}<input bind:value={current.title} on:keydown={(e)=>e.key==='Enter'&&rename()} /><button on:click={rename}>保存</button>{:else}<h2>{current.title}</h2><button class="link" on:click={()=>renameMode=true}>重命名</button>{/if}<span>{selectedModel?.name} · {selectedModel?.provider}</span></div>{:else}<h2>开始一个新会话</h2>{/if}<span>{currentUser.username}</span></header>
 {#if showUsage}<section class="usage-panel"><h3>我的用量</h3><label>起始日期 <input type="date" bind:value={from} on:change={loadUsage}/></label><label>结束日期 <input type="date" bind:value={to} on:change={loadUsage}/></label><select bind:value={usageModel} on:change={loadUsage}><option value="">全部模型</option>{#each models as model}<option value={model.id}>{model.name}</option>{/each}</select><table><thead><tr><th>模型</th><th>状态</th><th>Token</th></tr></thead><tbody>{#each usages as u}<tr><td>{models.find(m=>m.id===u.model_id)?.name||u.model_id}</td><td>{u.status}</td><td>{u.total_tokens ?? '未知'}</td></tr>{:else}<tr><td colspan="3">暂无调用记录</td></tr>{/each}</tbody></table></section>{/if}
 <div class="messages">{#if !current}<p class="welcome">选择一个有效模型，然后创建会话。模型在会话创建后固定不可切换。</p>{/if}{#each messages as message}<article class:assistant={message.role==='assistant'}><b>{message.role==='user'?'你':'助手'}</b><div class="content">{@html safeMarkdown(message.content)}</div>{#if message.status==='aborted'}<small>已中止</small>{/if}</article>{/each}</div>
 {#if notice}<div class="notice" role="status">{notice}</div>{/if}
 <form class="composer" on:submit|preventDefault={send}><textarea bind:value={prompt} placeholder={current?.status==='readonly'?'该会话仅可阅读':'输入消息；/error、/limit 可试验错误状态'} disabled={!current || current.status==='readonly' || !models.length}></textarea>{#if streamController}<button type="button" class="stop" on:click={stop}>停止生成</button>{:else}<button disabled={!current || current.status==='readonly' || !prompt.trim() || !models.length}>发送</button>{/if}</form></section></main>
{/if}

<style>
 :global(*){box-sizing:border-box}:global(body){margin:0;background:#f7f7f8;color:#202123;font:14px system-ui,-apple-system,sans-serif}.login{min-height:100vh;display:grid;place-items:center}.login section{width:min(400px,90vw);background:white;padding:32px;border-radius:12px;box-shadow:0 8px 30px #0001}.login h1{margin:0}.login form,label{display:grid;gap:7px;margin:14px 0}input,textarea,select{border:1px solid #d4d4d8;border-radius:7px;padding:9px;font:inherit}button{border:0;border-radius:7px;padding:9px 12px;background:#2563eb;color:white;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.error,.notice{padding:10px;border-radius:7px;background:#fee2e2;color:#991b1b}.app{height:100vh;display:grid;grid-template-columns:260px 1fr}.app aside{display:flex;flex-direction:column;padding:12px;background:#202123;color:white}.app aside header,.chat-head{display:flex;justify-content:space-between;align-items:center}.link{padding:4px;background:transparent;color:inherit}.new{margin:16px 0;background:#343541;text-align:left}.empty{color:#d1d5db}.app nav{overflow:auto;flex:1}.app nav div{display:flex}.app nav div button:first-child{flex:1;text-align:left;background:transparent}.app nav .chosen{background:#343541;border-radius:6px}.app nav small{float:right;color:#a1a1aa}.icon{background:transparent}.usage{background:transparent;border:1px solid #555}.chat{min-width:0;display:flex;flex-direction:column;height:100vh}.chat-head{padding:14px 24px;border-bottom:1px solid #e5e5e5}.chat-head h2{display:inline;margin:0 8px 0 0}.chat-head span{color:#6b7280;font-size:12px}.messages{overflow:auto;flex:1;padding:24px max(8%,24px)}article{max-width:760px;margin:0 auto 22px;padding:14px;border-radius:9px;background:#eef2ff}article.assistant{background:white}.content :global(pre){overflow:auto;padding:10px;background:#18181b;color:#f4f4f5;border-radius:6px}.content :global(code){font-family:ui-monospace,monospace}.welcome{text-align:center;color:#6b7280;margin-top:20vh}.composer{display:flex;gap:10px;padding:16px max(8%,24px);border-top:1px solid #e5e5e5;background:white}.composer textarea{resize:none;min-height:48px;flex:1}.stop{background:#dc2626}.notice{margin:0 max(8%,24px)}.usage-panel{position:absolute;right:24px;top:60px;z-index:1;width:420px;background:white;border:1px solid #ddd;border-radius:10px;padding:16px;box-shadow:0 8px 30px #0002}.usage-panel label{display:inline-grid;margin-right:8px}.usage-panel table{width:100%;margin-top:10px;border-collapse:collapse}.usage-panel th,.usage-panel td{padding:7px;border-bottom:1px solid #eee;text-align:left}@media(max-width:700px){.app{grid-template-columns:80px 1fr}.app aside strong,.app aside .new,.app aside .usage,.app nav button:first-child{font-size:0}.app aside .new::first-letter{font-size:18px}.chat-head{padding:12px}.usage-panel{right:5px;width:calc(100% - 90px)}}
</style>
